version: '3'

networks:
  traefik:
    external: true

services:
  codeserver:
    container_name: code-server
    image: lscr.io/linuxserver/code-server:latest
    restart: unless-stopped
    volumes:
      - ./config:/home/coder/.config
    networks:
      - traefik
    environment:
      - DOCKER_USER=$USER
      - PUID=1000
      - GUID=1000
      - DEFAULT_WORKSPACE=../
    labels:
      - traefik.enable=true
      - traefik.http.services.code-server.loadbalancer.server.port=8443

      - traefik.http.routers.code-server-http.rule=host(`code.${DOMAINNAME}`)
      - traefik.http.routers.code-server-http.entrypoints=web
      - traefik.http.routers.code-server-http.middlewares=redirect-https
      - traefik.http.routers.code-server-http.service=code-server

      - traefik.http.routers.code-server-https.rule=Host(`code.${DOMAINNAME}`)
      - traefik.http.routers.code-server-https.entrypoints=websecure
      - traefik.http.routers.code-server-https.tls=true
      - traefik.http.routers.code-server-https.service=code-server
