version: '3'

networks:
  traefik:
    external: true

services:

  nextclouddb:
    container_name: nextclouddb
    image: mariadb:10.5
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - traefik
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOTPASSWORD}
      - MYSQL_PASSWORD=${PASSWORD}
      - MYSQL_DATABASE=${DATABASE}
      - MYSQL_USER=${DBUSER}
    labels:
      - com.centurylinklabs.watchtower.monitor-only="true"

  nextcloud:
    container_name: nextcloud
    image: nextcloud:latest
    restart: unless-stopped
    links:
      - nextclouddb
    volumes:
      - ./config:/var/www/html/config
      - ./apps:/var/www/html/custom_apps
      - ${DATA}/nc-data:/var/www/html/data
    networks:
      - traefik
    environment:
      - MYSQL_PASSWORD=${PASSWORD}
      - MYSQL_DATABASE=${DATABASE}
      - MYSQL_USER=${DBUSER}
      - MYSQL_HOST=${DBHOST}
    labels:
      - com.centurylinklabs.watchtower.monitor-only="true"
      - traefik.enable=true
      - traefik.http.services.nextcloud.loadbalancer.server.port=80

      - traefik.http.routers.nextcloud-http.rule=Host(`nextcloud.${DOMAINNAME}`)
      - traefik.http.routers.nextcloud-http.entrypoints=web
      - traefik.http.routers.nextcloud-http.middlewares=redirect-https
      - traefik.http.routers.nextcloud-http.service=nextcloud

      - traefik.http.routers.nextcloud-https.rule=Host(`nextcloud.${DOMAINNAME}`)
      - traefik.http.routers.nextcloud-https.entrypoints=websecure
      - traefik.http.routers.nextcloud-https.tls=true
      - traefik.http.routers.nextcloud-https.service=nextcloud