version: '3'


networks:
  traefik:
    external: true


services:
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      - PMA_ARBITRARY=1
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.services.phpmyadmin.loadbalancer.server.port=80

      - traefik.http.routers.phpmyadmin-http.rule=Host(`phpmyadmin.${DOMAINNAME}`)
      - traefik.http.routers.phpmyadmin-http.entrypoints=web
      - traefik.http.routers.phpmyadmin-http.middlewares=redirect-https
      - traefik.http.routers.phpmyadmin-http.service=phpmyadmin

      - traefik.http.routers.phpmyadmin-https.rule=Host(`phpmyadmin.${DOMAINNAME}`)
      - traefik.http.routers.phpmyadmin-https.entrypoints=websecure
      - traefik.http.routers.phpmyadmin-https.tls=true
      - traefik.http.routers.phpmyadmin-https.service=phpmyadmin