version: '3'

networks:
  traefik:
    external: true

services:

  technitium:
    container_name: technitium
    image: technitium/dns-server:latest
    restart: unless-stopped
    volumes:
      - ./config:/etc/dns/config
    networks:
      - traefik
    ports:
      - 5380:5380/tcp
      - 53:53/udp
      - 53:53/tcp
    environment:
      - DNS_SERVER_DOMAIN=$DOMAINNAME #The primary domain name used by this DNS Server to identify itself.
      # - DNS_SERVER_ADMIN_PASSWORD=password #DNS web console admin user password.
      # - DNS_SERVER_ADMIN_PASSWORD_FILE=password.txt #The path to a file that contains a plain text password for the DNS web console admin user.
      # - DNS_SERVER_PREFER_IPV6=false #DNS Server will use IPv6 for querying whenever possible with this option enabled.
      # - DNS_SERVER_OPTIONAL_PROTOCOL_DNS_OVER_HTTP=false #Enables DNS server optional protocol DNS-over-HTTP on TCP port 8053 to be used with a TLS terminating reverse proxy like nginx.
      # - DNS_SERVER_RECURSION=AllowOnlyForPrivateNetworks #Recursion options: Allow, Deny, AllowOnlyForPrivateNetworks, UseSpecifiedNetworks.
      # - DNS_SERVER_RECURSION_DENIED_NETWORKS=1.1.1.0/24 #Comma separated list of IP addresses or network addresses to deny recursion. Valid only for `UseSpecifiedNetworks` recursion option.
      # - DNS_SERVER_RECURSION_ALLOWED_NETWORKS=127.0.0.1, 192.168.1.0/24 #Comma separated list of IP addresses or network addresses to allow recursion. Valid only for `UseSpecifiedNetworks` recursion option.
      # - DNS_SERVER_ENABLE_BLOCKING=false #Sets the DNS server to block domain names using Blocked Zone and Block List Zone.
      # - DNS_SERVER_ALLOW_TXT_BLOCKING_REPORT=false #Specifies if the DNS Server should respond with TXT records containing a blocked domain report for TXT type requests.
      # - DNS_SERVER_FORWARDERS=1.1.1.1, 8.8.8.8 #Comma separated list of forwarder addresses.
      # - DNS_SERVER_FORWARDER_PROTOCOL=Tcp #Forwarder protocol options: Udp, Tcp, Tls, Https, HttpsJson.
    labels:
      - traefik.enable=true
      - traefik.http.services.technitium.loadbalancer.server.port=80

      - traefik.http.routers.technitium-http.rule=Host(`technitium.${DOMAINNAME}`)
      - traefik.http.routers.technitium-http.entrypoints=web
      - traefik.http.routers.technitium-http.middlewares=redirect-https
      - traefik.http.routers.technitium-http.service=technitium

      - traefik.http.routers.technitium-https.rule=Host(`technitium.${DOMAINNAME}`)
      - traefik.http.routers.technitium-https.entrypoints=websecure
      - traefik.http.routers.technitium-https.tls=true
      - traefik.http.routers.technitium-https.service=technitium